import { NextRequest, NextResponse } from "next/server";
import fs from "node:fs/promises";
import { existsSync, symlinkSync } from "node:fs";
import path from "node:path";
import { resolveGame, REAL_HUB_URL, REAL_RANKING_HOST } from "@/detector/config";
import { readBaseEnv } from "@/detector/base-env";
import { stopPreview, stopProcessesUsingDir } from "@/detector/preview-process";
import { resizeUploadToMatchTarget, resizeUploadToMatchRemote, type CropAnchor } from "@/detector/resize-upload";
import { applyTextSlot } from "@/detector/site-text";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// Fixed, single clone slot per game — regenerated (wiped + rebuilt) on
// every "Generate Clone" click rather than versioned, matching the
// "1 template -> 1 dev preview" flow from the project's original business
// goal, not a multi-clone manager. Keyed by gameId (not a single constant
// anymore) so switching games via ?game= doesn't clobber another game's
// clone/uploads.
export function getCloneDir(repoPath: string): string {
  return path.join(path.dirname(repoPath), "home-page-clone");
}

// Every "Generate clone" wipes CLONE_DIR and rebuilds it from repoPath
// (see copyRepoSkeleton) — without this, every operator-uploaded
// replacement would be lost on the next click, forcing a full re-upload
// every single test run. Mirrors CLONE_DIR's own relative layout (a local
// asset's targetPath, or "public/<localPath>" for an external one) so
// applyPersistedUploads can just overlay it wholesale.
function getUploadsDir(repoPath: string): string {
  return path.join(path.dirname(repoPath), "home-page-uploads");
}

async function persistUpload(repoPath: string, relativePath: string, buf: Buffer) {
  const dest = path.join(getUploadsDir(repoPath), relativePath);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, buf);
}

// External assets need more than the saved file re-applied: the source
// file(s) that hardcode the CDN URL also need the literal-string rewrite
// redone on every fresh copyRepoSkeleton (it only lives in the wiped
// CLONE_DIR, never in repoPath) — this manifest is what makes that
// possible without the operator resubmitting the external: field again.
type ExternalManifestEntry = { url: string; localPath: string; refFiles: string[] };
function getExternalManifestPath(repoPath: string): string {
  return path.join(path.dirname(repoPath), "home-page-uploads-manifest.json");
}

async function readExternalManifest(repoPath: string): Promise<Record<string, ExternalManifestEntry>> {
  try {
    return JSON.parse(await fs.readFile(getExternalManifestPath(repoPath), "utf-8"));
  } catch {
    return {};
  }
}

async function writeExternalManifestEntry(repoPath: string, entry: ExternalManifestEntry) {
  const manifest = await readExternalManifest(repoPath);
  manifest[entry.localPath] = entry;
  await fs.writeFile(getExternalManifestPath(repoPath), JSON.stringify(manifest, null, 2));
}

async function applyPersistedUploads(repoPath: string, cloneDir: string) {
  const uploadsDir = getUploadsDir(repoPath);
  if (existsSync(uploadsDir)) {
    await fs.cp(uploadsDir, cloneDir, { recursive: true });
  }
  const manifest = await readExternalManifest(repoPath);
  for (const { url, localPath, refFiles } of Object.values(manifest)) {
    const publicUrl = "/" + localPath.replace(/\\/g, "/");
    for (const refFile of refFiles) {
      const srcPath = path.join(cloneDir, refFile);
      if (!existsSync(srcPath)) continue;
      const content = await fs.readFile(srcPath, "utf-8");
      if (!content.includes(url)) continue;
      await fs.writeFile(srcPath, content.split(url).join(publicUrl));
    }
  }
}

// .vs/bin/obj are .NET's equivalent of node_modules/.next — regenerated by
// `dotnet build`/`dotnet run`, not part of the source being cloned. Copying
// them wastes time (found on quy-mon-quan: copying 42MB bin/ of many small
// files made the whole clone take 60s+) and is actively wrong to keep: a
// stale bin/obj can make `dotnet run` serve the OLD compiled DLLs instead of
// rebuilding from the freshly-patched source underneath them.
const SKIP_TOP_LEVEL = new Set(["node_modules", ".git", "dist", ".next", "deploy", ".vs", "bin", "obj"]);


async function rmWithRetry(dest: string) {
  // Regenerating while the clone's own preview dev server is still running
  // fails with EBUSY on Windows (Vite holds the directory). stopPreview()
  // handles anything this tool itself spawned; a short retry covers the
  // brief window between that process exiting and the OS releasing the
  // file handle.
  await stopPreview();
  await stopProcessesUsingDir(dest);
  let lastErr: unknown;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      await fs.rm(dest, { recursive: true, force: true });
      return;
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, 500));
    }
  }
  const message = lastErr instanceof Error ? lastErr.message : String(lastErr);
  throw new Error(
    `Could not remove the previous clone (${message}). If a preview dev server for it is running outside this tool (started manually in a terminal), stop that process first and try again.`
  );
}

async function copyRepoSkeleton(src: string, dest: string) {
  await rmWithRetry(dest);
  await fs.mkdir(dest, { recursive: true });

  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    if (SKIP_TOP_LEVEL.has(entry.name)) continue;
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    await fs.cp(srcPath, destPath, { recursive: true });
  }

  // Vite needs node_modules to run `npm run dev`; a full reinstall is slow
  // and unnecessary since the clone is source-identical to the original —
  // link to the original's node_modules instead of copying/reinstalling.
  const srcNodeModules = path.join(src, "node_modules");
  const destNodeModules = path.join(dest, "node_modules");
  if (existsSync(srcNodeModules)) {
    try {
      symlinkSync(srcNodeModules, destNodeModules, "junction");
    } catch {
      // Best-effort — if linking fails (permissions, etc.), the clone still
      // has real source files; the user can `npm install` there themselves.
    }
  }
}

// A slot's replacement image can arrive either as an uploaded File or, when
// the operator pastes a URL instead of picking a file, as a plain string —
// fetched server-side (not from the browser) so it isn't subject to the
// CDN's CORS policy.
async function readUploadBuffer(value: FormDataEntryValue): Promise<Buffer> {
  if (value instanceof File) {
    return Buffer.from(await value.arrayBuffer());
  }
  const url = typeof value === "string" ? value.trim() : "";
  if (!url) throw new Error("no file or URL provided");
  if (!/^https?:\/\//i.test(url)) throw new Error(`unsupported URL: ${url}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`could not fetch ${url} (${res.status})`);
  return Buffer.from(await res.arrayBuffer());
}

/** Replaces the host of `url`, keeping its scheme and path; falls back to https://domain. */
function withHost(url: string | undefined, domain: string): string {
  try {
    const u = new URL(url ?? "");
    return `${u.protocol}//${domain}${u.pathname.replace(/\/$/, "")}`;
  } catch {
    return `https://${domain}`;
  }
}

export async function POST(request: NextRequest) {
  try {
    const form = await request.formData();
    const gameIdField = form.get("gameId");
    const { repoPath } = resolveGame(typeof gameIdField === "string" ? gameIdField : undefined);
    const CLONE_DIR = getCloneDir(repoPath);

    await copyRepoSkeleton(repoPath, CLONE_DIR);
    await applyPersistedUploads(repoPath, CLONE_DIR);

    const filesReplaced: { targetPath: string; originalBytes: number; finalBytes: number; resized: boolean }[] = [];
    const externalReplaced: {
      id: string;
      url: string;
      localPath: string;
      refFilesPatched: string[];
      originalBytes: number;
      finalBytes: number;
      resized: boolean;
    }[] = [];
    const textReplaced: string[] = [];
    const warnings: string[] = [];
    const env = await readBaseEnv(repoPath);
    const baseEnvKeyCount = Object.keys(env).length;
    const overriddenKeys: string[] = [];

    for (const [key, value] of form.entries()) {
      if (key.startsWith("file:") && (value instanceof File || typeof value === "string")) {
        // key is "file:<{targetPaths, anchor}Json>" — one upload can map to
        // several physical files (e.g. a per-breakpoint asset's tablet +
        // desktop copies both come from injection.targetPaths for that
        // slot). anchor is the operator's manual crop-anchor override
        // ("attention" — sharp's auto-detect — when they didn't pick one).
        const { targetPaths, anchor }: { targetPaths: string[]; anchor: CropAnchor } = JSON.parse(
          key.slice("file:".length)
        );
        let uploadBuf: Buffer;
        try {
          uploadBuf = await readUploadBuffer(value);
        } catch (e) {
          warnings.push(`${targetPaths[0]}: ${e instanceof Error ? e.message : String(e)}`);
          continue;
        }
        for (const targetPath of targetPaths) {
          // targetPath is repo-relative, e.g. "public/assets/rank/1920/bg-rank.png"
          // Resize/compress to match THIS target's own real dimensions —
          // per-breakpoint variants (tablet vs desktop) have different real
          // sizes, so this is done per targetPath, not once per upload.
          const finalBuf = await resizeUploadToMatchTarget(uploadBuf, repoPath, targetPath, anchor);
          const destPath = path.join(CLONE_DIR, targetPath);
          await fs.mkdir(path.dirname(destPath), { recursive: true });
          await fs.writeFile(destPath, finalBuf);
          await persistUpload(repoPath, targetPath, finalBuf);
          filesReplaced.push({
            targetPath,
            originalBytes: uploadBuf.byteLength,
            finalBytes: finalBuf.byteLength,
            resized: finalBuf !== uploadBuf,
          });
        }
      } else if (key.startsWith("external:") && (value instanceof File || typeof value === "string")) {
        // External (CDN-hosted) assets have no local file to overwrite — save
        // the upload into the clone's public/ dir instead, then literal-string
        // replace the hardcoded external URL with the new root-relative path
        // in every source file that referenced it (same technique as the
        // fake-news fallback patching: rewrite the clone's own copy only).
        const {
          url,
          localPath,
          refFiles,
          anchor,
        }: { url: string; localPath: string; refFiles: string[]; anchor: CropAnchor } = JSON.parse(
          key.slice("external:".length)
        );
        let uploadBuf: Buffer;
        try {
          uploadBuf = await readUploadBuffer(value);
        } catch (e) {
          warnings.push(`${localPath}: ${e instanceof Error ? e.message : String(e)}`);
          continue;
        }
        // Fetch the CDN URL being replaced to read ITS dimensions, then resize
        // the upload to match — the same "never write an off-size asset"
        // guarantee local file replacement already has (resize-upload.ts),
        // just sourced from a network fetch instead of a repo file since
        // there's no local original to read here.
        const finalBuf = await resizeUploadToMatchRemote(uploadBuf, url, path.extname(localPath), anchor);
        const destPath = path.join(CLONE_DIR, "public", localPath);
        await fs.mkdir(path.dirname(destPath), { recursive: true });
        await fs.writeFile(destPath, finalBuf);
        await persistUpload(repoPath, path.join("public", localPath), finalBuf);
        await writeExternalManifestEntry(repoPath, { url, localPath, refFiles });

        const publicUrl = "/" + localPath.replace(/\\/g, "/");
        const refFilesPatched: string[] = [];
        for (const refFile of refFiles) {
          const srcPath = path.join(CLONE_DIR, refFile);
          if (!existsSync(srcPath)) continue;
          const content = await fs.readFile(srcPath, "utf-8");
          if (!content.includes(url)) continue;
          await fs.writeFile(srcPath, content.split(url).join(publicUrl));
          refFilesPatched.push(refFile);
        }
        externalReplaced.push({
          id: `${localPath}`,
          url,
          localPath: publicUrl,
          refFilesPatched,
          originalBytes: uploadBuf.byteLength,
          finalBytes: finalBuf.byteLength,
          resized: finalBuf !== uploadBuf,
        });
      } else if (key.startsWith("text:") && typeof value === "string") {
        const textId = key.slice("text:".length);
        if (await applyTextSlot(CLONE_DIR, repoPath, textId, value.trim())) {
          textReplaced.push(textId);
        }
      } else if (key.startsWith("param:")) {
        const envKey = key.slice("param:".length);
        if (envKey && typeof value === "string" && value.trim() !== "") {
          env[envKey] = value;
          overriddenKeys.push(envKey);
        }
      }
    }

    // Real backend, no fake data: hub keys → REAL_HUB_URL, ranking keys → the
    // real game-services host (scheme/path of the original value kept).
    const hubKeys = Object.keys(env).filter((k) => /(^|_)HUB$/i.test(k) && /^https?:\/\//i.test(env[k]));
    const rankingKeys = Object.keys(env).filter((k) => /(GAME_SERVICES?|SERVICE_GAME|RANKING_API)/i.test(k) && /^https?:\/\//i.test(env[k]));
    for (const k of hubKeys) env[k] = REAL_HUB_URL;
    for (const k of rankingKeys) env[k] = withHost(env[k], REAL_RANKING_HOST);
    overriddenKeys.push(...hubKeys, ...rankingKeys);
    if (hubKeys.length === 0) warnings.push("Không tìm thấy env key base URL của Hub — API hub vẫn dùng URL gốc.");
    if (rankingKeys.length === 0) warnings.push("Không tìm thấy env key base URL của Ranking — Ranking vẫn dùng URL gốc.");

    const envPath = path.join(CLONE_DIR, ".env.local");
    const envLines = Object.entries(env).map(([k, v]) => `${k}=${v}`);
    await fs.writeFile(envPath, envLines.join("\n") + "\n");

    return NextResponse.json({
      cloneDir: CLONE_DIR,
      filesReplaced,
      externalReplaced,
      textReplaced,
      envWritten: envLines.length,
      baseEnvKeyCount,
      overriddenKeys,
      warnings,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
