/**
 * The real dev backend (VITE_APP_HUB) returns 404 for /api/frontend/*
 * for this game — confirmed live, not a network/env problem (see project
 * history). Every one of these API functions already has a try/catch with
 * an empty-ish fallback (`return [];` / `return null;`); rather than
 * intercepting network calls, we patch those EXISTING fallback branches in
 * the clone's own copy of services/index.ts to return fake-but-plausible
 * data instead, so the news tab renders something to preview instead of
 * nothing. Only ever applied to the clone, never the source repo — and
 * re-applied on every "Generate Clone" since the clone is copied fresh
 * each time.
 */

export function buildMockNewsModuleSource(slideImagePaths: string[], gameName = "Game"): string {
  // Per-game name so two games' previews don't show the same (Phượng Hoàng) copy.
  const name = gameName.replace(/'/g, "");
  const slideEntries = slideImagePaths
    .map((p, i) => `  { image: '${p}', title: 'Slide demo ${i + 1}', link: '#' },`)
    .join("\n");

  return `// Auto-generated by the Clone tool — fake data for preview only.
// The real backend returns 404 for this game's /api/frontend/* routes;
// these fallbacks let the news tab render something instead of nothing.

export interface FakeCategory {
  id: number;
  title: string;
  slug: string;
}

export interface FakePost {
  id: number;
  title: string;
  slug: string;
  category_id: number;
  created_at: string;
  content: string;
}

export const FAKE_CATEGORIES: FakeCategory[] = [
  { id: 1, title: 'Tin Tức', slug: 'tin-tuc' },
  { id: 2, title: 'Sự Kiện', slug: 'su-kien' },
  { id: 3, title: 'Cập Nhật', slug: 'cap-nhat' },
];

export const FAKE_POSTS: FakePost[] = [
  {
    id: 1,
    title: '${name} chính thức mở cửa máy chủ mới',
    slug: 'mo-cua-may-chu-moi',
    category_id: 1,
    created_at: '2026-09-20T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo — placeholder xem giao diện] Máy chủ mới chính thức khai mở, tân thủ nhận ngay quà chào mừng khủng.</p>',
  },
  {
    id: 2,
    title: 'Sự kiện nạp đầu tiên x3 giá trị',
    slug: 'nap-dau-x3',
    category_id: 2,
    created_at: '2026-09-18T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Nạp lần đầu nhận ngay x3 giá trị thẻ nạp, áp dụng đến hết tuần.</p>',
  },
  {
    id: 3,
    title: '${name} — Cập nhật phiên bản 2.0',
    slug: 'cap-nhat-2-0',
    category_id: 3,
    created_at: '2026-09-15T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Phiên bản mới bổ sung tính năng mới cùng loạt trang bị mới.</p>',
  },
  {
    id: 4,
    title: '${name} — Giải đấu liên server mùa 3',
    slug: 'giai-dau-tong-mon-3',
    category_id: 2,
    created_at: '2026-09-10T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Đăng ký giải đấu liên server mùa 3, tổng giải thưởng lên đến 100 triệu đồng.</p>',
  },
  {
    id: 5,
    title: 'Hướng dẫn tân thủ 7 ngày đầu',
    slug: 'huong-dan-tan-thu',
    category_id: 1,
    created_at: '2026-09-05T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Lộ trình phát triển nhân vật tối ưu trong 7 ngày đầu gia nhập.</p>',
  },
  {
    id: 6,
    title: 'Bảo trì định kỳ và lộ trình phát triển',
    slug: 'bao-tri-dinh-ky',
    category_id: 3,
    created_at: '2026-09-01T09:00:00.000Z',
    content:
      '<p>[Dữ liệu demo] Thông báo lịch bảo trì định kỳ hàng tuần và các nội dung sắp ra mắt.</p>',
  },
];

// Generated at the same 560x450 aspect ratio NewsMainSlider's <img> declares
// (it has no width class, so it renders at the source image's own intrinsic
// size — an unrelated real asset here previously mismatched the fixed-size
// news panel next to it).
export const FAKE_SLIDES = [
${slideEntries}
];

// The helpers below are generic on purpose: each game types its own
// NewsPost / NewsCategory / Slide differently, and the patched fallbacks must
// compile against ANY of them (a build that fails on a fake-data type
// mismatch is worse than no fake data). T is inferred from the function's
// declared return type.
export function fakeCategories<T = unknown>(): T[] {
  return FAKE_CATEGORIES as unknown as T[];
}

export function fakeSlides<T = unknown>(): T[] {
  return FAKE_SLIDES as unknown as T[];
}

// categoryId may be missing (then every post is returned) or numeric-like.
export function fakePostsByCategory<T = unknown>(categoryId?: number | string | null, limit?: number): T[] {
  const id = categoryId === undefined || categoryId === null || categoryId === '' ? null : Number(categoryId);
  const list = id === null || Number.isNaN(id) ? FAKE_POSTS : FAKE_POSTS.filter((p) => p.category_id === id);
  return (typeof limit === 'number' ? list.slice(0, limit) : list) as unknown as T[];
}

// key is a slug or a numeric id depending on how the game fetches the detail.
export function getFakePostBySlug<T = unknown>(key: string | number): T | null {
  const k = String(key);
  const post = FAKE_POSTS.find((p) => p.slug === k || String(p.id) === k);
  if (!post) return null;
  const category = FAKE_CATEGORIES.find((c) => c.id === post.category_id);
  return { ...post, category } as unknown as T;
}
`;
}

// Parameter names of the function that encloses position \`index\` in \`code\`:
// handles both positional (categoryId: number, limit = 4) and destructured
// ({ category_id, limit = 4 }: {...}) signatures.
function enclosingParamNames(code: string, index: number): string[] {
  const before = code.slice(0, index);
  const re = /(?:async\s+)?\(([^()]*)\)\s*(?::[^=]*)?=>|function\s*\w*\s*\(([^()]*)\)/g;
  let last: RegExpExecArray | null = null;
  for (let m = re.exec(before); m; m = re.exec(before)) last = m;
  if (!last) return [];
  const list = (last[1] ?? last[2] ?? "").trim();
  if (!list) return [];
  // Split on top-level commas only (types like { a: string; b: number } and
  // object patterns contain commas/colons of their own).
  const parts: string[] = [];
  let depth = 0;
  let cur = "";
  for (const ch of list) {
    if ("{[(<".includes(ch)) depth++;
    if ("}])>".includes(ch)) depth--;
    if (ch === "," && depth === 0) {
      parts.push(cur);
      cur = "";
    } else cur += ch;
  }
  if (cur.trim()) parts.push(cur);
  const names: string[] = [];
  for (const part of parts) {
    const p = part.trim();
    if (p.startsWith("{")) {
      // destructured: take names from inside the pattern (before the type annotation)
      const close = p.indexOf("}");
      for (const item of p.slice(1, close).split(",")) {
        const n = item.trim().match(/^([A-Za-z_$][\w$]*)/);
        if (n) names.push(n[1]);
      }
    } else {
      const n = p.match(/^([A-Za-z_$][\w$]*)/);
      if (n) names.push(n[1]);
    }
  }
  return names;
}

export function patchServicesForFakeNews(content: string): string {
  let patched = content;

  // Prepend rather than anchor to an existing import line — a Vite game
  // imports its API base URL via a centralized `KEY_ENV` (`../utils/constant`),
  // but that's not universal: a Next.js game found in the wild reads
  // `process.env.NEXT_PUBLIC_*` inline with no such import at all, which
  // silently left this whole patch a no-op (the route regexes below matched
  // fine, but the replacement code referenced FAKE_* without ever having
  // imported them → ReferenceError at runtime). Prepending is always valid
  // regardless of what else the file imports or how it reads its config.
  patched =
    "import { fakeCategories, fakePostsByCategory, fakeSlides, getFakePostBySlug } from './mock-news-data';\n" +
    patched;

  // `;?` and `\(\w+\)` (not a hardcoded `error`/`e`) below because the exact
  // semicolon usage and catch-param name are code-style choices that vary
  // per repo (found a real no-semicolon Next.js game) — not part of the
  // pattern actually being matched (the route string + its empty-ish
  // fallback).

  // getCategories: `/api/frontend/home-categories` ... catch (x) { return []; }
  patched = patched.replace(
    /(home-categories`(?:(?!\nexport )[\s\S])*?catch \(\w+\) \{\s*)return \[\];?/,
    "$1return fakeCategories();"
  );

  // getpostNews: `/api/frontend/posts` (no slug) ... catch (x) { return []; }
  // The category/limit variable names differ per game (category_id vs
  // categoryId, limit or not) — read them from the enclosing function's own
  // signature instead of assuming one spelling.
  patched = patched.replace(
    /(\/api\/frontend\/posts`(?:(?!\nexport )[\s\S])*?catch \(\w+\) \{\s*)return \[\];?/,
    (whole, head: string, offset: number) => {
      const names = enclosingParamNames(patched, offset);
      const category = names.find((n) => /categor/i.test(n)) ?? "undefined";
      const limit = names.find((n) => /limit/i.test(n)) ?? "undefined";
      return `${head}return fakePostsByCategory(${category}, ${limit});`;
    }
  );

  // getSiteSlide: `/api/frontend/slides` ... catch (x) { return null; }
  patched = patched.replace(
    /(\/api\/frontend\/slides`(?:(?!\nexport )[\s\S])*?catch \(\w+\) \{\s*)return (?:null|\[\]);?/,
    "$1return fakeSlides();"
  );

  // getDetailPost: `/api/frontend/posts/${slug}` ... catch (x) { return null; }
  // or `return [];` — fallback shape (null vs empty array) isn't consistent
  // across repos either. The detail key may be a slug or an id, optionally
  // wrapped (encodeURIComponent(slug)).
  patched = patched.replace(
    /(\/api\/frontend\/posts\/\$\{([^}]*)\}`(?:(?!\nexport )[\s\S])*?catch \(\w+\) \{\s*)return (?:null|\[\]);?/,
    (whole, head: string, expr: string) => {
      const key = (expr.match(/[A-Za-z_$][\w$]*/g) ?? []).filter((w) => w !== "encodeURIComponent").pop() ?? "slug";
      return `${head}return getFakePostBySlug(${key});`;
    }
  );

  return patched;
}
