/**
 * Offline mode for a generated clone: every axios request the clone makes is
 * answered by a local fake adapter, so the preview never touches the real
 * backend (hub / game-services / login). Known endpoints get plausible data in
 * the shape the games already parse; anything else is rejected immediately so
 * each game's existing try/catch fallback runs without a network round-trip.
 *
 * Written into the clone only (services/mock-api.ts), never the source repo,
 * and re-applied on every "Generate Clone" like fake-news.
 */

export const MOCK_API_FILE = "mock-api.ts";

export function buildMockApiModuleSource(gameName = "Demo Game"): string {
  const name = JSON.stringify(gameName);
  return `// Auto-generated by the Clone tool — offline fake API for preview only.
import axios from 'axios';
import { FAKE_CATEGORIES, FAKE_POSTS, FAKE_SLIDES } from './mock-news-data';

const link = '#';
const SITE_CONFIG: Record<string, string> = {
  site_name: ${name},
  site_logo_url: '',
  web_domain: 'http://localhost',
  home_meta_title: ${name},
  home_meta_desc: '[Dữ liệu demo] Mô tả trang',
  home_meta_keywords: 'demo',
  share_title: ${name},
  share_desc: '[Dữ liệu demo] Mô tả chia sẻ',
  share_thumb: '',
  custom_config: '',
  ga_code: '',
  google_site_verification: '',
  fb_page_id: '',
  qrcode_img_link: '',
  intro_youtube_embed_link: '',
  ID_VIDEO_YOUTUBE: '',
  CHARACTER_VIDEO: '',
  news_tintuc_id: '1',
  news_tanthu_id: '1',
  news_vip_id: '2',
  // Home slider (SliderPC/SliderMB) reads JSON [{id, image_link}] from the config API.
  slide_home: JSON.stringify(FAKE_SLIDES.map((s, i) => ({ id: i + 1, image_link: s.image }))),
  loantinramat: '',
};
for (const k of [
  'download_android_link', 'download_apk_link', 'download_ios_link', 'download_pc_link',
  'fb_group_link', 'fb_page_link', 'page_event_url', 'page_giftcode_url', 'page_payment_url',
  'page_support_url', 'link_like_page', 'link_loan_tin', 'link_join_group', 'link_vote_app',
  'link_play_game', 'link_tiktok', 'link_h5', 'tiktok_link', 'tiktok_page_link', 'join_group',
  'like_page', 'landingVoteUrl', 'voteapp', 'voteapp5sao',
]) SITE_CONFIG[k] = link;

const RANK_NAMES = ['Long Thiên', 'Kiếm Vô Song', 'Bạch Y Tiên', 'Hắc Phong', 'Thanh Vân', 'Tuyết Nhi', 'Phong Lôi', 'Minh Nguyệt', 'Thiên Sát', 'Lạc Hà'];
function fakeRanking(scope: string) {
  const n = scope === 'area' ? 5 : 10;
  return RANK_NAMES.slice(0, n).map((name, i) => {
    const server = 'S' + (scope === 'area' ? 1 : i + 1);
    const power = 9800000 - i * 612345;
    return { Id: i + 1, id: i + 1, Name: name, name, Server: server, server, ServerName: server, server_name: server, Power: power, power };
  });
}

function ok(config: any, data: unknown) {
  return Promise.resolve({ data, status: 200, statusText: 'OK', headers: {}, config, request: {} });
}
function fail(config: any, status: number) {
  const response = { data: {}, status, statusText: 'Offline demo', headers: {}, config, request: {} };
  return Promise.reject(new axios.AxiosError('Offline demo (fake API)', status >= 500 ? 'ERR_BAD_RESPONSE' : 'ERR_BAD_REQUEST', config, {}, response as any));
}
function paramsOf(config: any): Record<string, any> {
  const out: Record<string, any> = { ...(config.params || {}) };
  const q = String(config.url || '').split('?')[1];
  if (q) new URLSearchParams(q).forEach((v, k) => { out[k] = v; });
  return out;
}
const wrap = (data: unknown) => ({ code: '0', success: true, message: 'ok', data });

async function fakeAdapter(config: any) {
  const path = String(config.url || '').split('?')[0];
  const p = paramsOf(config);
  let m: RegExpMatchArray | null;

  if (/\\/api\\/frontend\\/config$/.test(path)) return ok(config, wrap(SITE_CONFIG));
  if (/\\/api\\/frontend\\/slides$/.test(path)) return ok(config, wrap(FAKE_SLIDES));
  if (/\\/api\\/frontend\\/(home-)?categories$/.test(path)) return ok(config, wrap(FAKE_CATEGORIES));
  if (/\\/api\\/frontend\\/posts-related$/.test(path)) {
    const rest = FAKE_POSTS.filter((x) => String(x.id) !== String(p.post_id));
    return ok(config, wrap(rest.slice(0, Number(p.limit) || 5)));
  }
  if ((m = path.match(/\\/api\\/frontend\\/posts\\/([^/]+)$/))) {
    const key = decodeURIComponent(m[1]);
    const post = FAKE_POSTS.find((x) => x.slug === key || String(x.id) === key);
    if (!post) return fail(config, 404);
    return ok(config, wrap({ ...post, category: FAKE_CATEGORIES.find((c) => c.id === post.category_id) }));
  }
  if (/\\/api\\/frontend\\/posts$/.test(path)) {
    const cid = p.category_id === undefined || p.category_id === '' ? null : Number(p.category_id);
    const list = cid === null || Number.isNaN(cid) ? FAKE_POSTS : FAKE_POSTS.filter((x) => x.category_id === cid);
    return ok(config, wrap(list.slice(0, Number(p.limit) || list.length)));
  }
  if (/\\/Ranking\\/GetRanking$/i.test(path)) return ok(config, fakeRanking(String(p.scope || 'all')));
  if (/\\/oauth2\\/me$/.test(path)) return ok(config, { code: '1', data: null });
  if (/\\/landing\\/(GetGuilds|GetCountByArea)$/i.test(path)) return ok(config, []);
  return fail(config, 404);
}

// Instances made by axios.create() copy the defaults at creation time, so the
// adapter must be injected into create() too (baseAxios.ts etc. are evaluated
// after this module because they import it first).
(axios as any).defaults.adapter = fakeAdapter;
const originalCreate = axios.create.bind(axios);
(axios as any).create = (cfg?: any) => originalCreate({ ...(cfg || {}), adapter: fakeAdapter });

export {};
`;
}

/** Prepends the side-effect import so the adapter is installed before any axios call. */
export function prependMockApiImport(content: string, relativeImport: string): string {
  if (content.includes("mock-api")) return content;
  return `import '${relativeImport}/mock-api';\n` + content;
}
